#pragma once

#define ATLANTIS_NAMESPACE Atlantis

#define ATLANTIS_NAMESPACE_BEGIN namespace ATLANTIS_NAMESPACE{
#define ATLANTIS_NAMESPACE_END	}

#define USING_ATLANTIS using namespace ATLANTIS_NAMESPACE;


ATLANTIS_NAMESPACE_BEGIN
ATLANTIS_NAMESPACE_END