#pragma once

#define BIFROST_NAMESPACE Bifrost

#define BIFROST_NAMESPACE_BEGIN namespace BIFROST_NAMESPACE{
#define BIFROST_NAMESPACE_END }

#define USING_BIFROST using namespace BIFROST_NAMESPACE;

BIFROST_NAMESPACE_BEGIN
BIFROST_NAMESPACE_END