#pragma once

#define MAGALLANICA_NAMESPACE magallanica

#define MAGALLANICA_NAMESPACE_BEGIN namespace MAGALLANICA_NAMESPACE{
#define MAGALLANICA_NAMESPACE_END }

#define USING_MAGALLANICA using namespace MAGALLANICA_NAMESPACE;

MAGALLANICA_NAMESPACE_BEGIN
MAGALLANICA_NAMESPACE_END